export const SPEED = 288.167  // MPS, TRUE VALUE: 1,037.4 KPH
export const ALTITUDE = 10668  // meter, TRUE VALUE: 35,000 feet
export const ALTITUDE_45 = 13719  // meter, TRUE VALUE: 45,000 feet
export const HEIGHT_35 = 35000
export const HEIGHT_45 = 45000
export const DELAY_IN_START = 5  // the camera warm up time at the leg start (seconds)
export const MIN_TIME = 25  // minimum time to capture a target (seconds)
export const DTIME = 5  // dead time required between pictures (seconds)
export const INNERMOST_DIST = 24140.16  // inner radius of annuli (meter)
export const INNER_DIST = 80467.2  // inner radius of annuli (meter)
export const MIDDLE_DIST = 112654.08  // inner middle radius of annuli (meter)
export const OUTER_DIST = 128747.52  // outer middle radius of annuli (meter)
export const OUTERMOST_DIST = 193121.28  // outer radius of annuli (meter)
export const RADIUS = 8046.72  // TRUE VALUE: 5 miles
export const ALPHA_GIRD_DISTANCE = 2e-6  // bigger Alpha = Larger grid = less options
export const OPTIMAL_MODE = 0
export const WIND_DIRECTION = 0  // degrees
export const WIND_SPEED = 80  // knit
export const SQUNIT_ANGEL = 90  // degrees
export const ALTITUDE_FLY_ZONE = -430.5  // TAKE THE EARTH'S LOWEST POINT (meter)
export const DEFAULT_HEIGHT_TARGETS = 0  // lowest point on target (meter)
export const ALPHA_HIGH_LIMIT = 5  // when we adjust the alpha by the num targets then this is the max
export const ALPHA_LOW_LIMIT = 2  // same but min
export const MAX_TARGETS = 98
export const MIN_TARGETS = 1
export const ALPHA_PARAMETER = 1e-6
export const MIN_DANGEROUS_AREA = 850000000  // if the annulus area is under this than we remove the target in the filer_targets
export const MAX_LEGS_DRAW_CONNECTION = 20
export const LINE_OF_SIGHT_RES = 1  // resolution of line of sight calculation in meter
export const HEIGHT_DISCRETE_JUMPS = 305  // discrete height options spacing in m (ALTITUDE + N * HEIGHT_DISCRETE_JUMPS)
export const MAX_ALTITUDE = 15240  // 50K feet
export const MAX_TARGETS_PER_LEG = 10
export const DISTANCE_BEFORE_RISE_HEIGHT = 32186 // 20 mils in meters, before rise to leg up to 35K feet.